stages:
  - test
  - build
  - push
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  REGISTRY: docker.io
  DOCKERHUB_NAMESPACE: "66160155"
  BACKEND_IMAGE: $REGISTRY/$DOCKERHUB_NAMESPACE/notes-backend:latest
  FRONTEND_IMAGE: $REGISTRY/$DOCKERHUB_NAMESPACE/notes-frontend:latest

# 1. Stage Test
test_backend:
  stage: test
  image: node:18-alpine
  tags:
    - informatics
  script:
    - cd backend
    - npm install
    - npm test || echo "Backend test skipped"
  only:
    - main

test_frontend:
  stage: test
  image: node:18-alpine
  tags:
    - informatics
  script:
    - cd frontend
    - npm install
    - npm run lint || echo "Frontend lint skipped"
  only:
    - main

# 2. Stage Build:
build_images:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  tags:
    - informatics
  needs: ["test_backend", "test_frontend"]
  script:
    - docker build -t $BACKEND_IMAGE ./backend
    - docker build --build-arg VUE_APP_API_URL=http://10.5.3.213/api -t $FRONTEND_IMAGE ./frontend
    - docker save $BACKEND_IMAGE > backend.tar
    - docker save $FRONTEND_IMAGE > frontend.tar
  artifacts:
    paths:
      - backend.tar
      - frontend.tar
    expire_in: 1 hour
  only:
    - main

# 3. Stage Push
push_to_dockerhub:
  stage: push
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  tags:
    - informatics
  needs: ["build_images"]
  script:
    - docker load < backend.tar
    - docker load < frontend.tar
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker push $BACKEND_IMAGE
    - docker push $FRONTEND_IMAGE
  only:
    - main

# 4. Stage Deploy
deploy_to_k8s:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  tags:
    - informatics
  needs: ["push_to_dockerhub"]
  script:
    - export KUBECONFIG="$KUBE_CONFIG"
    # ใช้ sed เพื่อเปลี่ยนชื่อ Image ในไฟล์ YAML ให้เป็นตัวล่าสุดที่เราเพิ่ง Push ไป
    - sed -i "s|YOUR_BACKEND_IMAGE|$BACKEND_IMAGE|g" k8s/backend-deployment.yaml
    - sed -i "s|YOUR_FRONTEND_IMAGE|$FRONTEND_IMAGE|g" k8s/frontend-deployment.yaml
    - kubectl apply -f k8s/
    # บังคับให้ K8s ดึง Image ใหม่ล่าสุดมาใช้ (Rollout)
    - kubectl rollout restart deployment/frontend -n notesapp
    - kubectl rollout restart deployment/backend -n notesapp
  only:
    - main