# Project identification
sonar.projectKey=Pathamapo_simplest-note-web-app-backend
sonar.organization=pathamapornw
sonar.projectName=simplest-note-web-app
sonar.projectVersion=1.0
# Source code
sonar.sources=frontend/src,backend/src
sonar.sourceEncoding=UTF-8
# SonarCloud server URL
sonar.host.url=https://sonarcloud.io
# บอกทางไปหาไฟล์รายงานที่เราเพิ่งรันได้
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

# การตั้งค่าส่วนของ Test
# ระบุโฟลเดอร์ที่เก็บไฟล์เทสต์
sonar.tests=backend/test
sonar.test.inclusions=backend/test/**/*.test.js

# ข้ามการสแกนไฟล์ที่ไม่ใช่โค้ดที่เราเขียนเอง (ช่วยลดบัค 300 ตัว)
sonar.exclusions=**/node_modules/**, **/dist/**, **/coverage/**, backend/test/**
# ไม่นับไฟล์เทสต์เป็นส่วนหนึ่งของ Code Coverage
sonar.coverage.exclusions=backend/test/**/*.test.js