# Project identification
sonar.projectKey=Pathamapo_simplest-note-web-app-backend
sonar.organization=pathamapornw
sonar.projectName=simplest-note-web-app
sonar.projectVersion=1.0

# Source code
sonar.sources=frontend,backend
sonar.sourceEncoding=UTF-8

# Exclude test files from coverage
sonar.coverage.exclusions=**/__tests__/**,**/*.test.js