apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: notesapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pathamapornw/notesapp-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://10.5.3.213:27017/notesapp"