apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: notesapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pathamapornw/notesapp-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VUE_APP_API_URL
          value: "http://10.5.3.213/api"