apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: notesapp
spec:
  type: NodePort  # เปลี่ยนจาก ClusterIP เป็น NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # เพิ่มบรรทัดนี้เพื่อกำหนดพอร์ตเป็น 30000

