apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: notesapp
spec:
  type: ClusterIP  # เปลี่ยนจาก ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort : 31477
       