name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Test Backend
      - name: Test Backend
        run: |
          cd backend
          npm install
          npm test
        env:
          MONGO_URL: mongodb://localhost:27017/notesdb
          NODE_ENV: test

      # 4. SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Pathamapo_simplest-note-web-app-backend
            -Dsonar.organization=pathamapornw
            -Dsonar.sources=frontend,backend
            -Dsonar.coverage.exclusions=**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 5. Trivy Scan
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          exit-code: 0